### ISSUE TITLE
Plugin does resolve when using Play 2.7.3 and Scala 2.13.0

### ISSUE THREAD

**Issue by ChickenSniper** [playframework/play-soap#108] opened 2019-10-22 04:05 UTC
Here is my plugins.sbt

```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.7.3")

resolvers += Resolver.url("play-sbt-plugins", url("https://dl.bintray.com/playframework/sbt-plugin-releases/"))(Resolver.ivyStylePatterns)

addSbtPlugin("com.typesafe.sbt" % "sbt-play-soap" % "1.1.4")
```

And I have in my build.sbt

```
scalaVersion := "2.13.0"
```

I get this sbt error

```
sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.play#play-soap-client_2.13;1.1.4: not found
```

**Comment by ihostage** [comment] 2019-10-22 10:43
Hi, @ChickenSniper!
This is a duplicate of https://github.com/playframework/play-soap/issues/54.
Scala 2.13 will be supported on version `1.1.5`.

**Closed** 2019-10-22 11:30 UTC
Labels: duplicate

**Comment by fkoehler** [comment] 2019-11-08 09:47
I can not find the release of 1.1.5 yet in https://dl.bintray.com/playframework/sbt-plugin-releases/com.typesafe.sbt/sbt-play-soap/ for scala 2.13. Any chance this will get released?

**Comment by ihostage** [comment] 2019-11-08 11:14
@fkoehler Yes, of course, 1.1.5 will be released. 😉 
@marcospereira @renatocaval Can you find a time to back on our discussion on the forum about release Play SOAP and review my PRs?

**Comment by sergiuszkierat** [comment] 2020-01-15 05:32
@ihostage any news about [1.1.5](https://github.com/playframework/play-soap/milestone/1)?
